
var express = require('express');
var mongoose = require('mongoose');
var User = require('/models/users.js');
var bodyParser = require('body-parser');
var app = express();
var port = 8888;
var path = __dirname + '/views/';

/*Database connection - MongoDB*/
//Created from the command earlier. Ensure this is done on the first_db instance
var username = 'shaoliujia';
var password = 'shao';

var dbHost = 'localhost';
var dbPort = '27017';
var database = 'first_db';

var url = 'mongodb://' + username + ':' + password + '@' + dbHost + ':' + dbPort + '/' + database;
console.log('mongodb connection = ' + url);

mongoose.connect(url, function(err) {
    if(err) {
        console.log('connection error: ', err);
    } else {
        console.log('connection successful');
    }
});
/*Body parser*/
app.use(bodyParser.urlencoded({
    extended: true
}));
/******
* Declare all models here
*/
//User model the object id is automaticlly generated by the system
/*var UserSchema = new mongoose.Schema({
     username: String,
     password: String
 });

var User = mongoose.model('user', UserSchema);
*/
/*
 * set different routers
 */
app.get('/', function (req, res, next) {
 res.sendFile( path + 'index.html');
});

app.get('/register', function (req, res, next) {
 res.sendFile( path + 'register.html');
});

app.post('/register', function (req, res, next) {
  User.create(req.body, function(err, saved) {
      if(err) {
          console.log(err);
          res.json({ message : err });
      } else {
          res.json({ message : "User successfully registered!"});
      }
  });
});

app.listen(port, function() {
 console.log('Server running at port ' + port);
});
